# Generated by Django 4.0.6 on 2022-07-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TargetURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_url', models.URLField()),
                ('short_url', models.CharField(max_length=7)),
                ('lifetime', models.URLField()),
            ],
            options={
                'ordering': ['-lifetime'],
            },
        ),
    ]
